version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6380:6379"
