version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - redis
    networks:
      - red_local

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - red_local

networks:
  red_local:
    driver: bridge
